### PR TITLE
Updates and fixes

### PR DESCRIPTION
**Pull request by kosmiq**
Hi,

Saw your commits on a PR in the original project. I added this as a PR there and thought I'd drop it here as well if you're still using this project.

This updates it to Sage 8.5.0, adds your commits with a bit of refactoring, adds namespaces and some cleaning. Also aligns better with WordPress-Core code style (but not completely). Also fixes devdeps in bower and npm.

### CODE REVIEW

**Comment by chuckn246** [comment]
Thanks!

**Comment by kosmiq** [comment]
Might add that I've only done limited testing so far. But it compiles fine with gulp and the basics seem to work. Your changes should work as before.

**Comment by chuckn246** [comment]
Sounds good! 

I haven't messed with this for a little while, but will do some testing and commit hopefully by the weekend. 

I really appreciate it!

**Comment by chuckn246** [comment]
Thanks again, sorry it took so long haha

**Pull request closed without merging**
